@eshop_api_host_address = https://localhost:7111

POST {{eshop_api_host_address}}/Product/
Accept: application/json
Content-Type: application/json

{
  "id": "389fb8e8-3962-4dcf-a765-b3f546c2e212",
  "name": "iPhone 16 Pro",
  "price": 100.0
}

###


GET {{eshop_api_host_address}}/Product/389fb8e8-3962-4dcf-a765-b3f546c2e212
Accept: application/json
Tenant.Id: 1011 
Site.Id: 2022
Correlation.ID: 389fb8e8-3962-4dcf-a765-b3f546c2e111

###

GET {{eshop_api_host_address}}/Product/
Accept: application/json

###


GET {{eshop_api_host_address}}/WeatherForecast?pageSize=5&pageIndex=1